---
# Running the Sonata GK FUNCTIONS (Docker container)

- name: GATEKEEPER FUNCTIONS - running Docker containers
  docker_container:
    name: son-gtkfnct
    image: sonatanfv/son-gtkfnct
    env:
      CATALOGUES_URL: http://{{ public_ip }}:4002/catalogues/api/v2
      RACK_ENV: integration
    state: started
    ports: "5500:5500"
    restart_policy: "unless-stopped"
    volumes:
      - /var/log/sonata:/var/log/son-gtkfnct
    log_driver: syslog

- wait_for: host=0.0.0.0 port=5500 timeout=30 delay=10 state=started
