---
# Running the Sonata GK PACKAGES (Docker container)

- name: GATEKEEPER PACKAGES - running Docker containers
  docker_container:
    name: son-gtkpkg
    image: sonatanfv/son-gtkpkg
    env:
      CATALOGUES_URL: http://{{ public_ip }}:4002/catalogues/api/v2
      RACK_ENV: integration
    state: started
    ports: "5100:5100"
    restart_policy: "unless-stopped"
    volumes:
      - /var/log/sonata:/var/log/son-gtkpkg
    log_driver: syslog

- wait_for: host=0.0.0.0 port=5100 timeout=30 delay=10 state=started
